DROP DATABASE IF EXISTS silwal;

CREATE DATABASE silwal;
USE silwal;

CREATE TABLE user(
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	level ENUM('1', '2') NOT NULL,
	ready BOOLEAN NULL DEFAULT 1,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	creator VARCHAR(255) NOT NULL,
	PRIMARY KEY(email)
)Engine=InnoDB;

CREATE TABLE tokens(
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL,
	token VARCHAR(255) NOT NULL,
	used BOOLEAN NOT NULL DEFAULT 0,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY(username) REFERENCES user(email) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(id), INDEX(username), INDEX(used)
)Engine=InnoDB;

CREATE TABLE hostel(
	id INT NOT NULL AUTO_INCREMENT,
	hostelNo VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	capacity INT NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	creator VARCHAR(255) NULL,
	CONSTRAINT FOREIGN KEY(creator) REFERENCES user(email) ON DELETE SET NULL ON UPDATE CASCADE,
	PRIMARY KEY(id), UNIQUE(title), INDEX(capacity), UNIQUE(hostelNo)
)Engine=InnoDB;

CREATE TABLE room(
	id INT NOT NULL AUTO_INCREMENT,
	roomNo VARCHAR(255) NOT NULL,
	hostel VARCHAR(255) NOT NULL,
	capacity INT NOT NULL,
	price DOUBLE NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	creator VARCHAR(255) NULL,
	CONSTRAINT FOREIGN KEY(creator) REFERENCES user(email) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY(hostel) REFERENCES hostel(hostelNo) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE(hostel, roomNo), INDEX(capacity), INDEX(price),
	PRIMARY KEY(id), UNIQUE(roomNo)
)Engine=InnoDB;

CREATE TABLE resident(
	admNo VARCHAR(255) NOT NULL,
	fname VARCHAR(255) NOT NULL,
	lname VARCHAR(255) NOT NULL,
	othernames VARCHAR(255) NULL,
	phone VARCHAR(255) NOT NULL,
	parentPhone VARCHAR(255) NOT NULL,
	nationalId INT NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	creator VARCHAR(255) NULL,
	CONSTRAINT FOREIGN KEY(creator) REFERENCES user(email) ON DELETE SET NULL ON UPDATE CASCADE,
	PRIMARY KEY(admNo), INDEX(fname), INDEX(lname), UNIQUE(phone), UNIQUE(nationalId)
)Engine=InnoDB;

CREATE TABLE booking(
	id INT NOT NULL AUTO_INCREMENT,
	resident VARCHAR(255) NULL,
	room VARCHAR(255) NULL,
	occupants INT NOT NULL,
	paid DOUBLE NOT NULL,
	credit DOUBLE NOT NULL,
	year INT NOT NULL,
	startMonth ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC') NOT NULL,
	endMonth ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC') NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	creator VARCHAR(255) NULL,
	CONSTRAINT FOREIGN KEY(creator) REFERENCES user(email) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY(resident) REFERENCES resident(admNo) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY(room) REFERENCES room(roomNo) ON UPDATE CASCADE ON DELETE SET NULL,
	PRIMARY KEY(id), INDEX(year), INDEX(startMonth), INDEX(endMonth), UNIQUE(resident, room, year, startMonth, endMonth),
	INDEX(occupants), INDEX(credit)
)Engine=InnoDB;

CREATE TABLE residentRoom(
	id INT NOT NULL AUTO_INCREMENT,
	resident VARCHAR(255) NOT NULL,
	room VARCHAR(255) NOT NULL,
	year INT NOT NULL,
	startMonth ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC') NOT NULL,
	endMonth ENUM('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC') NOT NULL,
	amount DOUBLE NOT NULL,
	PRIMARY KEY(id), UNIQUE(resident, room, startMonth, endMonth),
	INDEX(resident), INDEX(room), INDEX(startMonth), INDEX(endMonth)
)Engine=InnoDB;